### ISSUE TITLE
Field with empty space for char data type while binding Dataset

### ISSUE THREAD

**Issue by tramesh2009** [Embarcadero/IB.NETDataProvider#12]
Hi,

I got empty space for char data type field while binding Dataset

How to trim the space for char data type fields while fetching record?

Thank You

**Comment by jeffovercash** [comment]
In the last release, I added a connection string property and a IBDatabase property called TruncateChar.  By default it is false, but when set true will right trim all char datatypes.  VarChar's are not trimmed.

truncate_char is for the connectionstring level, TruncateChar is the IBDatabase property.  At this time it only has that level of granularity because the person requesting it was fine with everything at the IBDatabase level behaving the same.
